# Generated by Django 5.2.16 on 2026-07-17 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cookbooks', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookbook',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='cookbooks', to='recipes.recipe'),
        ),
    ]
